"""initial schema

Revision ID: d3fa24a0a7ea
Revises:
Create Date: 2026-03-13 15:45:37.388606

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3fa24a0a7ea"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "church",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("pco_service_type_id", sa.String(length=50), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_church_slug"), "church", ["slug"], unique=True)
    op.create_table(
        "search_cache",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("query", sa.String(length=500), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "query", name="uq_search_cache_platform_query"),
    )
    op.create_table(
        "youtube_quota_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("units_used", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "church_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("church_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verification_token", sa.String(length=255), nullable=True),
        sa.Column("email_verification_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_reset_token", sa.String(length=255), nullable=True),
        sa.Column("password_reset_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_church_user_church_id"), "church_user", ["church_id"], unique=False)
    op.create_table(
        "pco_connection",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("church_id", sa.UUID(), nullable=False),
        sa.Column("auth_method", sa.String(length=20), nullable=False),
        sa.Column("app_id_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("secret_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("oauth_access_token_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("oauth_refresh_token_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_successful_call_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("church_id"),
    )
    op.create_table(
        "playlist",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("church_id", sa.UUID(), nullable=False),
        sa.Column("pco_plan_id", sa.String(length=50), nullable=False),
        sa.Column("pco_plan_date", sa.Date(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("external_playlist_id", sa.String(length=255), nullable=True),
        sa.Column("external_playlist_url", sa.String(length=1000), nullable=True),
        sa.Column("last_known_track_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("church_id", "pco_plan_id", "platform", name="uq_playlist_church_plan_platform"),
    )
    op.create_index(op.f("ix_playlist_church_id"), "playlist", ["church_id"], unique=False)
    op.create_table(
        "streaming_connection",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("church_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("access_token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("refresh_token_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_user_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("church_id", "platform", name="uq_streaming_connection_church_platform"),
    )
    op.create_index(op.f("ix_streaming_connection_church_id"), "streaming_connection", ["church_id"], unique=False)
    op.create_table(
        "song_mapping",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("church_id", sa.UUID(), nullable=False),
        sa.Column("pco_song_id", sa.String(length=50), nullable=False),
        sa.Column("pco_song_title", sa.String(length=500), nullable=False),
        sa.Column("pco_song_artist", sa.String(length=500), nullable=True),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("track_id", sa.String(length=255), nullable=False),
        sa.Column("track_title", sa.String(length=500), nullable=False),
        sa.Column("track_artist", sa.String(length=500), nullable=True),
        sa.Column("matched_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["matched_by_user_id"], ["church_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("church_id", "pco_song_id", "platform", name="uq_song_mapping_church_song_platform"),
    )
    op.create_index(op.f("ix_song_mapping_church_id"), "song_mapping", ["church_id"], unique=False)
    op.create_table(
        "sync_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("church_id", sa.UUID(), nullable=False),
        sa.Column("playlist_id", sa.UUID(), nullable=True),
        sa.Column("sync_trigger", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("songs_total", sa.Integer(), nullable=False),
        sa.Column("songs_matched", sa.Integer(), nullable=False),
        sa.Column("songs_unmatched", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlist.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_log_church_id"), "sync_log", ["church_id"], unique=False)
    op.create_table(
        "user_session",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("church_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["church_id"], ["church.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["church_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_session_church_id"), "user_session", ["church_id"], unique=False)
    op.create_index(op.f("ix_user_session_user_id"), "user_session", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_session_user_id"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_church_id"), table_name="user_session")
    op.drop_table("user_session")
    op.drop_index(op.f("ix_sync_log_church_id"), table_name="sync_log")
    op.drop_table("sync_log")
    op.drop_index(op.f("ix_song_mapping_church_id"), table_name="song_mapping")
    op.drop_table("song_mapping")
    op.drop_index(op.f("ix_streaming_connection_church_id"), table_name="streaming_connection")
    op.drop_table("streaming_connection")
    op.drop_index(op.f("ix_playlist_church_id"), table_name="playlist")
    op.drop_table("playlist")
    op.drop_table("pco_connection")
    op.drop_index(op.f("ix_church_user_church_id"), table_name="church_user")
    op.drop_table("church_user")
    op.drop_table("youtube_quota_usage")
    op.drop_table("search_cache")
    op.drop_index(op.f("ix_church_slug"), table_name="church")
    op.drop_table("church")
    # ### end Alembic commands ###
